#!/bin/bash
#
# Copyright 2014 Google Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Wait 60 seconds before actually turning the screen off. Till then we have a
# black background managed by xsecurelock's main process anyway.
sleep 60

# This is run in a setsid'd background process so xsecurelock's SIGTERM doesn't
# interrupt the xset operation.
(
  trap '' TERM
  exec xset s activate dpms force off
) &
exec sleep 3600
